#!/bin/sh
# learnings-index.sh — regenerate learnings/INDEX.md from frontmatter.
# POSIX sh. Outputs content to stdout AND writes learnings/INDEX.md.
# Idempotent: running twice produces byte-identical output.

set -eu

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
LEARNINGS="$ROOT/learnings"
TMPDIR_BASE="${TMPDIR:-/tmp}"

# awk helper: extract a frontmatter field value from a file.
# Usage: get_field <file> <field>
get_field() {
    awk -v field="$2:" '
        /^---$/ { if (fm == 0) { fm = 1; next } else { exit } }
        fm && index($0, field) == 1 {
            sub(/^[^:]+: */, "")
            print
            exit
        }
    ' "$1"
}

# Extract mission IDs from the Recurrence log section of a file.
# Looks for lines matching: (mission `<id>`)
get_recurrences() {
    awk '
        /^## Recurrence log/ { in_log = 1; next }
        /^## / && in_log { exit }
        in_log {
            line = $0
            while (match(line, /\(mission `[^`]+`\)/)) {
                chunk = substr(line, RSTART, RLENGTH)
                gsub(/^\(mission `|`\)$/, "", chunk)
                print chunk
                line = substr(line, RSTART + RLENGTH)
            }
        }
    ' "$1"
}

# Extract the mission ID from "Implemented in mission `<id>`" line.
get_implemented_in() {
    awk '
        match($0, /Implemented in mission `[^`]+`/) {
            chunk = substr($0, RSTART, RLENGTH)
            gsub(/^Implemented in mission `|`$/, "", chunk)
            print chunk
            exit
        }
    ' "$1"
}

# Build one INDEX.md line for a learning entry.
# $1 = subdir (patterns|anti-patterns|proposals), $2 = file path
build_entry() {
    subdir="$1"
    file="$2"
    basename_md="$(basename "$file")"
    slug="${basename_md%.md}"

    name="$(get_field "$file" "name")"
    desc="$(get_field "$file" "description")"
    from="$(get_field "$file" "introduced_in_mission")"

    # Build suffix
    suffix=""

    if [ "$subdir" = "proposals" ]; then
        status="$(get_field "$file" "status")"
        if [ -z "$status" ]; then
            status="open"
        fi
        case "$status" in
            accepted|closed|implemented)
                impl="$(get_implemented_in "$file")"
                if [ -n "$impl" ]; then
                    suffix="($status in $impl; from \`$from\`)"
                else
                    suffix="($status; from \`$from\`)"
                fi
                ;;
            *)
                suffix="($status; from \`$from\`)"
                ;;
        esac
    else
        # patterns and anti-patterns: check for recurrences
        recurrences="$(get_recurrences "$file")"
        if [ -n "$recurrences" ]; then
            # Build "recurred in `a` and `b`" string
            recur_str=""
            count=0
            prev=""
            while IFS= read -r mid; do
                count=$((count + 1))
                if [ -n "$prev" ]; then
                    recur_str="${recur_str}\`${prev}\` and "
                fi
                prev="$mid"
            done <<EOF
$recurrences
EOF
            # append the last one
            recur_str="${recur_str}\`${prev}\`"
            # if only one, strip the trailing " and "
            if [ $count -eq 1 ]; then
                recur_str="\`${prev}\`"
            fi
            suffix="(from \`$from\`; recurred in $recur_str)"
        else
            suffix="(from \`$from\`)"
        fi
    fi

    # Output: sort-key TAB line (sort key = name, lowercased for stable alpha sort)
    sortkey="$(printf '%s' "$name" | tr '[:upper:]' '[:lower:]')"
    printf '%s\t- [%s](%s/%s) — %s %s\n' "$sortkey" "$slug" "$subdir" "$basename_md" "$desc" "$suffix"
}

# Generate a section. $1 = subdir, $2 = section title
generate_section() {
    subdir="$1"
    title="$2"
    dir="$LEARNINGS/$subdir"
    tmpfile="$TMPDIR_BASE/learnings-idx-$$-${subdir}"

    printf '## %s\n\n' "$title"

    # Collect entries into tmp file for sorting
    rm -f "$tmpfile"

    found=0
    if [ -d "$dir" ]; then
        for f in "$dir"/*.md; do
            # Handle empty directory (glob expands to literal pattern)
            [ -e "$f" ] || continue
            found=1
            build_entry "$subdir" "$f" >> "$tmpfile"
        done
    fi

    if [ "$found" = "0" ]; then
        printf '_(empty)_\n'
    else
        # Sort by the tab-separated sort key, then strip the key
        sort "$tmpfile" | while IFS="$(printf '\t')" read -r _key line; do
            printf '%s\n' "$line"
        done
    fi

    rm -f "$tmpfile"
    printf '\n'
}

# ---- Main output ----

generate_output() {
    printf '# Learnings Index\n\n'
    printf '> Auto-regenerated by `scripts/learnings-index.sh`. Run it after adding or modifying any entry under `learnings/{patterns,anti-patterns,proposals}/`.\n\n'

    generate_section "patterns"      "Patterns"
    generate_section "anti-patterns" "Anti-patterns"
    generate_section "proposals"     "Proposals"
}

# Write to file and also emit to stdout
generate_output | tee "$LEARNINGS/INDEX.md"
